<?= $this->contentEntry()->open() ?>
<div dojoType="p4cms.mobile.Book"
        paginate="{sourceNode: '.source', pageOneExtraConfig: {targetNode: '.details-container', columns: 1, outputAllOnFail: false}}">
    <div dojoType="p4cms.mobile.Page" selected="true">
        <div class="mblViewContent cover">
            <?
            $helper = $this->contentEntry();
            $fields = $helper->getRenderedFields();

            if (in_array('image', $fields)) {
                print $helper->element('image');
            }
            if (in_array('title', $fields)) {
                print $helper->element('title');
            }
            ?>
            <div class='details-container'></div>
        </div>
    </div>
    <div class="source" style="display: none;">
        <?
        $fields = array_diff($fields, array('image', 'title'));
        foreach ($fields as $field) {
            print $helper->element($field);
        }
        ?>
    </div>
</div>
<?= $this->contentEntry()->close() ?>
