<?
// get data grid namespace
$namespace  = $this->dataGrid()->getNamespace();

// data store url
$url        = $this->url(
    array(
        'module'        => 'workflow',
        'controller'    => 'index',
        'action'        => 'index',
        'format'        => 'json'
    )
);

// set up data grid columns
$columns = array(
    'label'             => array(
        'width'         => '30%'
    ),
    'states'            => array(
        'width'         => '31%',
        'formatter'     => 'p4cms.ui.grid.formatters.CommaJoin'
    ),
    'contentTypes'      => array(
        'label'         => 'Content Types',
        'width'         => '30%',
        'formatter'     => 'p4cms.ui.grid.formatters.CommaJoin'
    )
);
if (count($this->actions)) {
    $columns[] = $this->dataGrid()->getDefaultActionsColumn();
}

// set up footer buttons
$buttons = array(
    'Add Workflow'      => array(
        'attribs'       => array(
            'class'     => 'add-button',
            'onclick'   => $namespace . '.Utility.openFormDialog("add");'
        )
    ),
    'Reset to Defaults' => array(
        'attribs'       => array(
            'onclick'   => $namespace . '.Utility.confirmReset();'
        )
    )
);

// array with tooltip dialogs attached to the grid fields
$fieldTooltips = array(
    array(
        'sourceField'   => 'description',
        'attachField'   => 'label'
    )
);

print $this->dataGrid(
    $namespace,
    array(
        'form'          => $this->form,
        'url'           => $url,
        'pageSize'      => $this->pageSize,
        'actions'       => $this->actions,
        'columns'       => $columns,
        'footer'        => array(
            'buttons'       => $buttons
        ),
        'attribs'       => array(
            'disableSort'   => array('_item', 'states', 'contentTypes'),
            'fieldTooltips' => $fieldTooltips
        )
    )
);