<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->headMeta() ?>
<?= $this->headTitle() ?>
<?= $this->dojo() ?>
<?= $this->headScript() ?>
<?= $this->headLink() ?>
<?= $this->headStyle() ?>
</head>

<body class='claro
 <?=$this->layout()->getLayout()?>
 <?=$this->request()->getModuleName()?>-module
 <?=$this->request()->getControllerName()?>-controller
 <?=$this->request()->getActionName()?>-action'>
<?=$this->toolbar()?>
<?=$this->notifications()?>

<div id="header">
 <div class="container">
  <?= $this->region('logo') ?>
  <div id="nav">
   <?
   print $this->menu('primary', array(
       'maxDepth'    => 0,
       'beforeLabel' => '<span>',
       'afterLabel'  => '</span>'
   )); 
   ?>
  </div>
 </div>
</div>

<div id="main">
 <div class="container-outer">
  <?= $this->layout()->content ?>
 </div>
 <br class="clear"/>
 <div class="mountains"></div>
</div>

<div id="footer">
 <div class="container">
  <?= $this->region('footer-nav') ?>
  <hr/>
  <?= $this->region('footer') ?>
 </div>
</div>

</body>
</html>