<div class="steps">
    <div class="step<?= ($this->step == 1) ? ' current' : ''?>">
        <span class="label">1. Check Requirements</span><span class="arrow"></span>
    </div>
    <div class="step<?= ($this->step == 2) ? ' current' : ''?>">
        <span class="label">2. Site Storage</span><span class="arrow"></span>
    </div>
    <div class="step<?= ($this->step == 3) ? ' current' : ''?>">
        <span class="label">3. Administrator</span><span class="arrow"></span>
    </div>
    <div class="step<?= ($this->step == 4) ? ' current' : ''?>">
        <span class="label">4. Create Site</span><span class="arrow"></span>
    </div>
    <div class="step<?= ($this->step == 5) ? ' current' : ''?>">
        <span class="label">5. Summary</span><span class="arrow"></span>
    </div>
</div>