<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <?= $this->headTitle() ?>
 <?= $this->dojo() ?>
 <?= $this->headScript() ?>
 <?= $this->headLink() ?>
 <?= $this->headStyle() ?>
</head>
<body class='claro error-page'>

<div id="layout-main">
 <div id="layout-top">
  <div id="container">
   <div id="content">
