<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <?= $this->headMeta() ?>
 <?= $this->headTitle() ?>
 <?= $this->dojo() ?>
 <?= $this->headScript() ?>
 <?= $this->headLink() ?>
 <?= $this->headStyle() ?>
</head>
<body class='claro
 <?=$this->layout()->getLayout()?>
 <?=$this->request()->getModuleName()?>-module
 <?=$this->request()->getControllerName()?>-controller
 <?=$this->request()->getActionName()?>-action'>

<?=$this->toolbar()?>
<?=$this->notifications()?>

<?=$this->layout()->content ?>

</body>
</html>
